export const clientes = [
  {
    id: 1,
    nombres: "JORGE",
    apellidos: "GARCIA",
    documento: "12345678",
    tipoDocumento: "CC",
    grado: "bachiller",
    fechaNacimiento: "01/01/2000",
    estadoCivil: "Soltero",
  },
  {
    id: 2,
    nombres: "CARLOS",
    apellidos: "RODRIGUEZ",
    documento: "12345677",
    tipoDocumento: "CC",
    grado: "universitario",
    fechaNacimiento: "01/01/2001",
    estadoCivil: "casado",
  },
  {
    id: 3,
    nombres: "MARIA",
    apellidos: "LOPEZ",
    documento: "12345676",
    tipoDocumento: "CC",
    grado: "tecnico",
    fechaNacimiento: "01/01/2002",
    estadoCivil: "Soltero",
  },
  {
    id: 4,
    nombres: "TERESA",
    apellidos: "GONZALEZ GARCIA",
    documento: "12345675",
    tipoDocumento: "CC",
    grado: "tecnologico",
    fechaNacimiento: "01/01/2003",
    estadoCivil: "Soltero",
  },
];